name: Security Gates

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  security-gates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: security-gates
        uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
        needs: build
        permissions:
          actions: read
          contents: read
          security-events: write