
name: Security Gates

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
    permissions:
      actions: read
      contents: read
      security-events: write
