name: "your-build-action"
on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  your_build_job: # Varsayılan derleme veya başka bir işiniz. Buraya dokunulmadı.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Default Branch
        run: |
          echo ${{ github.event.repository.default_branch }}
          ls -la
          
  security-gates:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write # Güvenlik olaylarını yazmak için gerekli
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run Trendyol security gates action
        uses: Trendyol/security-actions@master 
        # Hata veren 'uses' satırını buradaki gibi değiştirdim. 
        # Bu satır, tüm bir workflow yerine repository'deki ana action'ı çalıştırır. 
        # Gerekirse bu 'uses' satırını, repository'deki belgelere göre düzenlemeniz gerekebilir.
