name: Build Workflow

on:
  push:
    branches:
      - main

jobs:

  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
    permissions:
      actions: read
      contents: read
      security-events: write


  build:
    needs: [security-gates]
    runs-on: ubuntu-latest

    steps:
      - name: Basit Echo İşlemi (Build)
        run: echo "Build İşlemi: Echolasana yav!"
