
on:
  workflow_call:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: read-all

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Workflow
        run: echo "Validation successful" 
        
  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
    permissions: 
      security-events: write
      id-token: write
