name: "your-build-action"
on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  your_build_job: # Assume that this your build or any other job
    runs-on: ubuntu-latest
    steps:
      - name: Print Default Branch
        run: |
          echo ${{ github.event.repository.default_branch }}
          ls -la
          
  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
    permissions:
      actions: read
      contents: read
      security-events: write # This is required for writing security events to built-in GitHub Security Dashboard
