name: "your-build-action"
on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  your_build_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Print Default Branch
        run: |
          echo ${{ github.event.repository.default_branch }}
          ls -la
          
  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
    permissions:
      actions: read
      contents: read
      security-events: write
    # The 'with' section is where you pass inputs to the reusable workflow
    # For example, if security-gates.yml expects an input named 'some_input'
    # with:
    #   some_input: 'some_value'
