name: Build Workflow

on:
  push:
    branches:
      - main

jobs:

  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
    permissions:
      actions: read
      contents: read
      security-events: write

  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - name: Run Build
        run: echo "Building project..."
