name: Deploy

on:
  push:
    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kaynak Kodunu Checkout Et
        uses: actions/checkout@v3

      - name: Security Gates Taramasını Çalıştır
        id: security
        uses: trendyol/security-actions/.github/actions/security-gates@v1.0.2
        with:
          example-input: "örnek değer"

      - name: Deploy İşlemini Gerçekleştir
        run: |
          echo "Deploy işlemi başlatılıyor..."
          ./deploy.sh
