name: Release Workflow

on:
  push:
    branches:
      - main

jobs:
 release:
    name: Release Job
    runs-on: ubuntu-latest
    steps:
      - name: Run Release
        run: echo "Releasing project..."
