name: Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:

  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
    permissions:
      actions: read
      contents: read
      security-events: write


  release:
    needs: [security-gates]
    runs-on: ubuntu-latest

    steps:
      - name: Basit Echo İşlemi (Release)
        run: echo "Release İşlemi: Echolasana yav!"
