name: CI/CD Pipeline
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3


  security-gates:
    uses: Trendyol/security-actions/.github/workflows/security-gates.yml@master
    needs: build
    permissions:
      actions: read
      contents: read
      security-events: write

